### PR TITLE
Redesign pricing table #162561701

### PR DESCRIPTION
**Pull request by jrubenoff**
I've deployed a [review app](https://sf-dahlia-pl-pricing.herokuapp.com/) for this.

### New components

**In "Atoms -> Tables"**

- Pricing Table Hero - Rental 
- Pricing Table Hero - Sale
- Pricing Table Listing - Rental
- Pricing Table Listing - SRO
- Pricing Table Listing - Sale With No Parking
- Pricing Table Listing - Sale With Parking Lease
- Pricing Table Listing - Sale With Parking

**In "Organisms"**
- Property Card - Rental
- Property Card - Sale
- Results - Sale

### Updated components
- "Property Hero" and "Results" patterns now use the new pricing tables.

- We still use the original Property Card pattern throughout the "Pages" section, so I renamed it to "Property Card Legacy."

### Other changes

- To give more space to the increased amount of text in the pricing tables, the thumbnails on the Buy and Rent pages are now `50%` instead of `55%.`

- [unrelated] I fixed the oddly-aligned Favorite button in the property hero on small screens

### CODE REVIEW

**Comment by akegan** [comment]
@jrubenoff one small question on the examples. Would it be possible to add another row to one of the tables in the examples? I'm curious what they look like on mobile with >1 row per unit type

**Comment by jrubenoff** [comment]
@akegan Alrighty, just added some rows to the "Pricing Table Hero - Listing" patterns.

**Comment by akegan** [comment]
getting this error on SRO partial:
image

Not sure if it's new or if it was like that before.

I don't see any additional rows on the property hero pricing table examples (e.g. https://sf-dahlia-pl-pricing.herokuapp.com/components/detail/property-hero--multifamily.html). Am I looking in the wrong place or do you maybe need to re-deploy?

**Comment by akegan** [comment]
For [pricing table hero - Sale](https://sf-dahlia-pl-pricing.herokuapp.com/components/detail/pricing-table-hero--sale.html), when I shrink to mobile view the column name changes from Sales price to "Min income" I don't think it will affect us using the pattern in the webapp, but might be good to fix:
Mobile:
image

non-mobile: 
image

**Comment by jrubenoff** [comment]
@akegan Cool, I'll try to fix those tonight!

Anything else you can think of?

**Comment by akegan** [comment]
@jrubenoff I think it looks good otherwise. Only other minor comment is that  "Price*s* with/without parking" looks a bit funny when it becomes the label for only one value. Not sure if it makes sense because there's the price and the HOA dues, or if we should just update the column name to say "price without parking" instead

**Comment by jrubenoff** [comment]
@akegan Alright, fixed those issues and re-deployed.

Please re-review!

**Comment by akegan** [comment]
@jrubenoff I don't see any new commits on this branch since 2 days ago. Did you push up your changes?

**Comment by jrubenoff** [comment]
@akegan How about now?

**Comment by akegan** [comment]
ok looks good! Did you re-deploy too? I don't think I have access to see your review app on heroku

**Comment by jrubenoff** [comment]
[This link works for me](https://sf-dahlia-pl-pricing.herokuapp.com/) in an incognito window...

**Comment by akegan** [comment]
I just meant that I can't see the app on heroku so I can't see when it was last deployed or what was deployed. The link works fine though!

Just quickly reviewed the designs with Emily and she noticed that the [reserved units](https://sf-dahlia-pl-pricing.herokuapp.com/components/detail/pricing-table-listing--reserved.html) look a bit funny. We're not sure where the orange dots are supposed to go 
image

image

**Comment by jrubenoff** [comment]
Thanks for catching! Looks like a browser bug. (I was testing on Firefox.)

Don't have time to re-deploy today but it should be fixed if you run it locally.

**Pull request merged**
