### PR TITLE
Dropdown Button

### PR DESCRIPTION
**Pull request by slowbot**
**States**
- adding color map for states: approved, processing, withdrawn, disqualified, leased, appealed, waitlisted
- adding variant classes is-"variant" for dropdown-menu_items

**Variants**
- adding checkboxes for multi select option
- adding separator to divide sets of list items

**Aria:**
- tab-index=-1 to dropdown menu
- aria-expanded=true/false on button
- aria-hidden=true/false on expanded menu
- aria-hidden=true to dropdown icon
- aria-selected=true/false for list item
- role="listbox" instead of "menu" to allow for aria-multiselectable to be added
- role="option" to each list item,
- role="separator" for divider
- added aria-activedescendant for focusable child elements

**Global updates to button conventions**
- can use either has-icon or has-icon--right and not both in conjunction.

### CODE REVIEW

**Comment by callaghanc** [comment]
@slowbot I added the Fabricator spacing work as its own commit here, thanks for helping me with that! 🙂

A couple questions on the dropdown buttons:

- From the Pivotal story AC: "Escape will close the dropdown". Currently I don't see anything change in the dropdown button or the dropdown menu's appearance/styles/attributes when pressing escape while focus is in the dropdown menu. Is that because the escape button behavior is supposed to be implemented in our JS? Or is the escape button behavior something that is implemented by browsers, in which case pressing escape should automatically change attributes/styles of the button or dropdown menu, like for example by changing the `aria-expanded` attribute to `false`? I'm not super familiar with the details of ARIA in this case.

- There's a bottom margin on the dropdown button that causes the dropdown menu to be offset below the button, instead of the dropdown menu having its top edge flush to the button's bottom edge, as seen in this mockup: https://projects.invisionapp.com/d/main#/console/12604116/264262977/preview. Is this on purpose? Or would the dropdown menu render flush to its toggling button when actually toggled via JS?

**Comment by creativecoder** [comment]
I can answer the first question: `esc` behavior and any other non-css interactivity will likely need to be implemented in JS (aka React). I don't believe any browsers implement behavior for `aria` features, they are informational attributes for screen readers.

**Comment by creativecoder** [comment]
@slowbot Please make sure that list is clear in the acceptance criteria/engineering notes for https://www.pivotaltracker.com/story/show/154784997

**Comment by callaghanc** [comment]
ok cool thanks guys

**Pull request merged**
